// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBfdx4jRo1V3cgHPMkeZ5CDw12OSeRcfEM',
    appId: '1:1097383654659:web:ba135b10ddb45adf326536',
    messagingSenderId: '1097383654659',
    projectId: 'note-app-019',
    authDomain: 'note-app-019.firebaseapp.com',
    storageBucket: 'note-app-019.appspot.com',
    measurementId: 'G-QCN4KY76NC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAb2eMSYvDD1cKq6FHVncXj77ihcYvwiec',
    appId: '1:1097383654659:android:8e03d19dd5a9abe1326536',
    messagingSenderId: '1097383654659',
    projectId: 'note-app-019',
    storageBucket: 'note-app-019.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJbCQzRLjAdtCAGadHGiy9hodVv7B2LPQ',
    appId: '1:1097383654659:ios:4bb89e80750105ea326536',
    messagingSenderId: '1097383654659',
    projectId: 'note-app-019',
    storageBucket: 'note-app-019.appspot.com',
    iosBundleId: 'noteapp.example.noteApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBJbCQzRLjAdtCAGadHGiy9hodVv7B2LPQ',
    appId: '1:1097383654659:ios:4bb89e80750105ea326536',
    messagingSenderId: '1097383654659',
    projectId: 'note-app-019',
    storageBucket: 'note-app-019.appspot.com',
    iosBundleId: 'noteapp.example.noteApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBfdx4jRo1V3cgHPMkeZ5CDw12OSeRcfEM',
    appId: '1:1097383654659:web:46cbf18892aaf66b326536',
    messagingSenderId: '1097383654659',
    projectId: 'note-app-019',
    authDomain: 'note-app-019.firebaseapp.com',
    storageBucket: 'note-app-019.appspot.com',
    measurementId: 'G-TX8SR91YGD',
  );
}
