// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBkwxw9Jz5XayAbX3Qj0jCR1rv_zOLohY0',
    appId: '1:150218557947:web:e84e323ccbe86cd824e35e',
    messagingSenderId: '150218557947',
    projectId: 'notes-flutter-1019',
    authDomain: 'notes-flutter-1019.firebaseapp.com',
    storageBucket: 'notes-flutter-1019.appspot.com',
    measurementId: 'G-35LY82FRV8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCfnT_ZL5rPUAuwS-FE6MeIphmNk3JiGVw',
    appId: '1:150218557947:android:7df4bc66c137c55724e35e',
    messagingSenderId: '150218557947',
    projectId: 'notes-flutter-1019',
    storageBucket: 'notes-flutter-1019.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD87TPWhLyVAMrmiIyoYr2H2k_Zw-uxjXU',
    appId: '1:150218557947:ios:495e69e55f5f603624e35e',
    messagingSenderId: '150218557947',
    projectId: 'notes-flutter-1019',
    storageBucket: 'notes-flutter-1019.appspot.com',
    iosBundleId: 'com.notes.notes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD87TPWhLyVAMrmiIyoYr2H2k_Zw-uxjXU',
    appId: '1:150218557947:ios:495e69e55f5f603624e35e',
    messagingSenderId: '150218557947',
    projectId: 'notes-flutter-1019',
    storageBucket: 'notes-flutter-1019.appspot.com',
    iosBundleId: 'com.notes.notes',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBkwxw9Jz5XayAbX3Qj0jCR1rv_zOLohY0',
    appId: '1:150218557947:web:0624694d3054792524e35e',
    messagingSenderId: '150218557947',
    projectId: 'notes-flutter-1019',
    authDomain: 'notes-flutter-1019.firebaseapp.com',
    storageBucket: 'notes-flutter-1019.appspot.com',
    measurementId: 'G-0DQXFEJPY6',
  );

}